# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x05proto\"\x1d\n\ractionrequest\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1e\n\x0e\x61\x63tionresponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0b\x61\x63tiontoken\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\x0c\x61\x63tionresult\x12\x0e\n\x06result\x18\x01 \x01(\t2\x84\x01\n\x0cRegisterData\x12;\n\nDoRegister\x12\x14.proto.actionrequest\x1a\x15.proto.actionresponse\"\x00\x12\x37\n\ncheckToken\x12\x12.proto.actiontoken\x1a\x13.proto.actionresult\"\x00\x62\x06proto3')
)




_ACTIONREQUEST = _descriptor.Descriptor(
  name='actionrequest',
  full_name='proto.actionrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='proto.actionrequest.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='actionresponse',
  full_name='proto.actionresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='proto.actionresponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=82,
)


_ACTIONTOKEN = _descriptor.Descriptor(
  name='actiontoken',
  full_name='proto.actiontoken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='proto.actiontoken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=112,
)


_ACTIONRESULT = _descriptor.Descriptor(
  name='actionresult',
  full_name='proto.actionresult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.actionresult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['actionrequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['actionresponse'] = _ACTIONRESPONSE
DESCRIPTOR.message_types_by_name['actiontoken'] = _ACTIONTOKEN
DESCRIPTOR.message_types_by_name['actionresult'] = _ACTIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

actionrequest = _reflection.GeneratedProtocolMessageType('actionrequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.actionrequest)
  ))
_sym_db.RegisterMessage(actionrequest)

actionresponse = _reflection.GeneratedProtocolMessageType('actionresponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.actionresponse)
  ))
_sym_db.RegisterMessage(actionresponse)

actiontoken = _reflection.GeneratedProtocolMessageType('actiontoken', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONTOKEN,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.actiontoken)
  ))
_sym_db.RegisterMessage(actiontoken)

actionresult = _reflection.GeneratedProtocolMessageType('actionresult', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESULT,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:proto.actionresult)
  ))
_sym_db.RegisterMessage(actionresult)



_REGISTERDATA = _descriptor.ServiceDescriptor(
  name='RegisterData',
  full_name='proto.RegisterData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoRegister',
    full_name='proto.RegisterData.DoRegister',
    index=0,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkToken',
    full_name='proto.RegisterData.checkToken',
    index=1,
    containing_service=None,
    input_type=_ACTIONTOKEN,
    output_type=_ACTIONRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTERDATA)

DESCRIPTOR.services_by_name['RegisterData'] = _REGISTERDATA

# @@protoc_insertion_point(module_scope)
