# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class RegisterDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoRegister = channel.unary_unary(
        '/proto.RegisterData/DoRegister',
        request_serializer=data__pb2.actionrequest.SerializeToString,
        response_deserializer=data__pb2.actionresponse.FromString,
        )
    self.checkToken = channel.unary_unary(
        '/proto.RegisterData/checkToken',
        request_serializer=data__pb2.actiontoken.SerializeToString,
        response_deserializer=data__pb2.actionresult.FromString,
        )


class RegisterDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoRegister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RegisterDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoRegister': grpc.unary_unary_rpc_method_handler(
          servicer.DoRegister,
          request_deserializer=data__pb2.actionrequest.FromString,
          response_serializer=data__pb2.actionresponse.SerializeToString,
      ),
      'checkToken': grpc.unary_unary_rpc_method_handler(
          servicer.checkToken,
          request_deserializer=data__pb2.actiontoken.FromString,
          response_serializer=data__pb2.actionresult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.RegisterData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
